server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/kndb0608"
    username: root
    password: root

jwt:
  signerKey: "xqQJf+UGrMrAYBbJDtVw+LwgosCbXZFEiXMiVniMLeJwa7Hndlg+QAIinfy+SRw8"
