server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "xqQJf+UGrMrAYBbJDtVw+LwgosCbXZFEiXMiVniMLeJwa7Hndlg+QAIinfy+SRw8"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in seconds
